// aicheck scans published, non-AI wallpapers and conservatively detects
// images that were clearly generated by an AI model. It fetches preview_url
// into local memory and sends those bytes to Claude; original_url is never
// selected, downloaded, or passed to the model.
//
// Usage:
//
//	./aicheck                                      # dry-run
//	./aicheck --commit                             # persist high-confidence matches
//	./aicheck --commit --limit 10                  # canary
//	./aicheck --commit --created-after 2026-08-09T15:00:00Z
package main

import (
	"context"
	"errors"
	"flag"
	"fmt"
	"io"
	"log"
	"mime"
	"net/http"
	"strings"
	"time"

	"gorm.io/driver/postgres"
	"gorm.io/gorm"

	"github.com/wallpaper/backend/internal/config"
	"github.com/wallpaper/backend/internal/model"
	"github.com/wallpaper/backend/internal/pkg/llm"
	"github.com/wallpaper/backend/internal/repo"
)

const maxPreviewBytes = 5 * 1024 * 1024

var errPreviewTooLarge = errors.New("preview exceeds 5 MiB limit")

type wallpaperRow struct {
	ID         int64
	PreviewURL string
}

func main() {
	var (
		commit        bool
		limit         int
		pause         time.Duration
		minConfidence float64
		createdAfter  string
		createdBefore string
	)
	flag.BoolVar(&commit, "commit", false, "write high-confidence AI classifications to the DB")
	flag.IntVar(&limit, "limit", 0, "process at most N wallpapers (0 = unlimited)")
	flag.DurationVar(&pause, "pause", 400*time.Millisecond, "delay between API calls")
	flag.Float64Var(&minConfidence, "min-confidence", 0.85, "minimum confidence required to set is_ai_generated")
	flag.StringVar(&createdAfter, "created-after", "", "only process rows created at or after this RFC3339 timestamp")
	flag.StringVar(&createdBefore, "created-before", "", "only process rows created before this RFC3339 timestamp")
	flag.Parse()

	if minConfidence < 0 || minConfidence > 1 {
		log.Fatal("--min-confidence must be between 0 and 1")
	}

	cfg, err := config.Load()
	if err != nil {
		log.Fatal("load config: ", err)
	}
	if cfg.Anthropic.APIKey == "" {
		log.Fatal("ANTHROPIC_API_KEY is not set in env")
	}

	db, err := gorm.Open(postgres.Open(cfg.DB.DSN()), &gorm.Config{})
	if err != nil {
		log.Fatal("connect db: ", err)
	}
	ctx := context.Background()

	var rows []wallpaperRow
	q := db.WithContext(ctx).
		Table("wallpapers").
		Select("id, preview_url").
		Where("status = ?", model.WallpaperStatusPublished).
		Where("is_ai_generated = false").
		Where("preview_url <> ''").
		Where("file_type LIKE 'image/%'").
		Order("id ASC")
	if createdAfter != "" {
		t, err := time.Parse(time.RFC3339, createdAfter)
		if err != nil {
			log.Fatalf("invalid --created-after: %v", err)
		}
		q = q.Where("created_at >= ?", t)
	}
	if createdBefore != "" {
		t, err := time.Parse(time.RFC3339, createdBefore)
		if err != nil {
			log.Fatalf("invalid --created-before: %v", err)
		}
		q = q.Where("created_at < ?", t)
	}
	if limit > 0 {
		q = q.Limit(limit)
	}
	if err := q.Find(&rows).Error; err != nil {
		log.Fatal("query wallpapers: ", err)
	}

	fmt.Printf("found %d non-AI wallpapers with previews to assess\n", len(rows))
	fmt.Printf("automatic threshold: %.2f\n", minConfidence)
	if !commit {
		fmt.Println("dry-run — pass --commit to set is_ai_generated=true")
	}
	if len(rows) == 0 {
		return
	}

	llmClient := llm.New(cfg.Anthropic.APIKey, repo.NewLLMUsageRepo(db))
	httpClient := &http.Client{Timeout: 45 * time.Second}

	var assessed, marked, skipped, failed int
	for i, row := range rows {
		image, mediaType, err := downloadPreview(ctx, httpClient, row.PreviewURL)
		if err != nil {
			fmt.Printf("[%d/%d] id=%d DOWNLOAD ERR: %v\n", i+1, len(rows), row.ID, err)
			failed++
			continue
		}

		assessment, err := llmClient.AssessAIGenerated(ctx, image, mediaType)
		if err != nil {
			fmt.Printf("[%d/%d] id=%d ASSESS ERR: %v\n", i+1, len(rows), row.ID, err)
			failed++
			continue
		}
		assessed++

		shouldMark := assessment.IsAIGenerated && assessment.Confidence >= minConfidence
		decision := "not AI"
		if assessment.IsAIGenerated && !shouldMark {
			decision = "AI? below threshold"
		}
		if shouldMark {
			decision = "AI"
		}
		fmt.Printf("[%d/%d] id=%d → %s (%.2f) — %s\n",
			i+1, len(rows), row.ID, decision, assessment.Confidence, assessment.Notes)

		if shouldMark && commit {
			result := db.WithContext(ctx).Table("wallpapers").
				Where("id = ? AND is_ai_generated = false", row.ID).
				Update("is_ai_generated", true)
			if result.Error != nil {
				fmt.Printf("[%d/%d] id=%d DB UPDATE ERR: %v\n", i+1, len(rows), row.ID, result.Error)
				failed++
				continue
			}
			if result.RowsAffected == 0 {
				fmt.Printf("[%d/%d] id=%d SKIP (already changed)\n", i+1, len(rows), row.ID)
				skipped++
				continue
			}
		}
		if shouldMark {
			marked++
		}
		if pause > 0 {
			time.Sleep(pause)
		}
	}

	fmt.Println(strings.Repeat("-", 60))
	fmt.Printf("done: %d assessed, %d AI matches, %d skipped, %d failed\n", assessed, marked, skipped, failed)
}

func downloadPreview(ctx context.Context, client *http.Client, previewURL string) ([]byte, string, error) {
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, previewURL, nil)
	if err != nil {
		return nil, "", fmt.Errorf("build request: %w", err)
	}
	req.Header.Set("User-Agent", "WallpaperExchange-AICheck/1.0")

	resp, err := client.Do(req)
	if err != nil {
		return nil, "", fmt.Errorf("fetch preview: %w", err)
	}
	defer resp.Body.Close()
	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		return nil, "", fmt.Errorf("fetch preview: HTTP %d", resp.StatusCode)
	}

	data, err := io.ReadAll(io.LimitReader(resp.Body, maxPreviewBytes+1))
	if err != nil {
		return nil, "", fmt.Errorf("read preview: %w", err)
	}
	if len(data) == 0 {
		return nil, "", errors.New("preview response is empty")
	}
	if len(data) > maxPreviewBytes {
		return nil, "", errPreviewTooLarge
	}

	mediaType, _, _ := mime.ParseMediaType(resp.Header.Get("Content-Type"))
	if !isSupportedImageType(mediaType) {
		mediaType = http.DetectContentType(data)
	}
	if !isSupportedImageType(mediaType) {
		return nil, "", fmt.Errorf("unsupported preview media type %q", mediaType)
	}
	return data, mediaType, nil
}

func isSupportedImageType(mediaType string) bool {
	switch mediaType {
	case "image/jpeg", "image/png", "image/gif", "image/webp":
		return true
	default:
		return false
	}
}
